name: Build, Analyze, Scan

on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    name: Build
    runs-on: [self-hosted]
    steps:
      - name: Pre-cleanup
        run: sudo rm -rf /home/ubuntu/actions-runner/_work/TIC-TAC-TOE/TIC-TAC-TOE/.scannerwork

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      - name: Fix permissions
        run: sudo chmod -R 755 /home/ubuntu/actions-runner/_work/TIC-TAC-TOE/TIC-TAC-TOE

      - name: Deploy to container
        run: |
          docker stop game
          docker rm game

      - name: Update kubeconfig
        run: aws eks --region us-east-2 update-kubeconfig --name EKS_CLOUD

      - name: Deploy to kubernetes
        run: kubectl delete -f deployment-service.yml

      - name: Send a Slack Notification
        if: always()
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#githubactions-eks'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
